// Generated by CoffeeScript 1.6.2
var HackController, YesDirective, hackapp;

HackController = function($scope) {
  return $scope.state = 'maybe';
};

YesDirective = function() {
  return {
    templateUrl: 'yes.html'
  };
};

hackapp = angular.module('hackapp', []);

hackapp.controller('HackController', ['$scope', HackController]);

hackapp.directive('yes', [YesDirective]);
