// Generated by CoffeeScript 1.6.2
var HackController, hackapp;

HackController = function($scope) {};

hackapp = angular.module('hackapp', []);

hackapp.controller('HackController', ['$scope', HackController]);
